language: java
services:
  - docker
jdk:
  - openjdk14
addons:
  sonarcloud:
    organization: "oknozor"
    token:
      secure: "sLRoIL2p7UBuQbRngJnMSu3IGx+o3ojDEnIatsu6I/zsGEP+zEKwqke37AOBdFTDc+jEBvVK1xSDwXkl9UZI6ARc1ZVRw9aQ9SzODdILsPE4CL/V2xJtmEXgmV/Igvm2jLSdQK0lD92DuJw4Gb9kbhnpx/uIVprRU53pomORzTsh7xVZOI+KBxbTiwcVFyqMr2Abouh0Hmqw+UNU6XU5SQnGlT66unuI9HCxVPTRZGA94agrwPq/H67j7MPGzefHkK3zgEgg/ds14c+/aqCqj7zy1OLpwx/kjPapUsHtGGPRWbGS32ZWr3wMZEGX7y/GhLD31JX/ljrIKSPEvhU/KFzLj7Oh2n40S8tXbFsdyFrRCXFYbYbHthjrm0ddbp+v8WneW0wRN+3WyaNDF4gMMT72Eag6MvS0vBWVj38fsvSTmKG3/GJz8mlw4VnGfpyYLScibE3gv3QGv1trU1a2D7w3saFUgFMerLqRBjn3ba3X2BiEMJFpYl8pA8mCDEfFK9QfczW4eD4tDTgVkIxmrjFTGAIXarW/CxS/ItWms0r7r+pFwWp/Gc8btpAEmjuLRYfz9B9kG8t6DTiiv5jfGTTnXUJKe0HSmiWXHi3gt76ReHvLK2wAeZrSgFynVGu/Ud3yIiguWqgkEtn9mhKX9ybV0Xjny6gRV7c1JDVisU0="
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=oknozor_omdb-spring-demo